
title: Mal Jin — Data & AI
description: A collection of applied research and development projects exploring advanced methods in data science, machine learning, and AI-driven analytics to solve real-world challenges across diverse domains.
baseurl: "" # Leave empty for username.github.io
url: "https://maljin042.github.io/" # Change to your GitHub Pages URL

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"